 const data = {
   contents: [
     {
      _id: "1",
       profileImage: "/image/Screenshot (13).png",
       profileName: "Oscar Inspires",
       userHandle: "iOscarInspires",
       textArea: "this is the very basic level of coding and i am glad this project is going out very smoothly even more than i expect, exclusive perf with all the amazing fragrance that you can't imagine",
       mainImage:    "/image/THINK AND CODE P.png",
       brandName: "MAGA Nigeria",
       position: "President",
       level: "National",
       platform: "pdp",
       approve: "1.5m",
       reject: "32k",
       fair:   "fair",
       good: "good",
       best: "best",
       unacceptable: "unacceptable",
       undecided: "undecided",
       numFair: "3k",
            numGood: "100",
            numBest: "1.5m",
            numUnacceptable: "12k",
            numUndecided: "4",
       bannerImage: "/image/THINK AND CODE P.png",
       info: "I am a Biomedical Technologist, CEO Think and Code Academy",
       userLocation: "Jos, Plateau",
       birthday: "May 15, 1990",
       joined: "December 2020",
       Admiring: "900",
       Admiriers: "1.5m"
     },
        {
          _id: "2",
         profileImage: "/image/Screenshot (13).png",
         profileName: "Lake Woods",
         userHandle: "iLakeWoods",
         textArea: "this is the very basic level of coding and i am glad this project is going out very smoothly even more than i expect, exclusive perf with all the amazing fragrance that you can't imagine",
         mainImage: "/image/WIN_20200723_15_43_50_Pro.jpg",
         brandName: "MAGA Nigeria",
         position: "President",
         level: "National",
         platform: "pdp",
         approve: "1.5m",
         reject: "32k",
         fair:   "fair",
       good: "good",
       best: "best",
       unacceptable: "unacceptable",
       undecided: "undecided",
       numFair: "3k",
            numGood: "100",
            numBest: "1.5m",
            numUnacceptable: "12k",
            numUndecided: "4",
         bannerImage: "/image/THINK AND CODE P.png",
         info: "I am a Biomedical Technologist, CEO Think and Code Academy",
         userLocation: "Jos, Plateau",
         birthday: "May 15, 1990",
         joined: "December 2020",
         Admiring: "900",
         Admiriers: "1.5m"
        },
        {
          _id: "3",
            profileImage: "/image/Screenshot (13).png",
            profileName: "MaryHoldings",
            userHandle: "iMaryHoldings",
            textArea:"this is the very basic level of coding and i am glad this project is going out very smoothly even more than i expect, exclusive perf with all the amazing fragrance that you can't imagine",
            mainImage: "/image/Screenshot_20200413-191114.jpg",
            brandName: "MAGA Nigeria",
            position: "President",
            level: "National",
            platform: "pdp",
            approve: "1.5m",
            reject: "32k",
            fair:   "fair",
       good: "good",
       best: "best",
       unacceptable: "unacceptable",
       undecided: "undecided",
       numFair: "3k",
            numGood: "100",
            numBest: "1.5m",
            numUnacceptable: "12k",
            numUndecided: "4",
            bannerImage: "/image/THINK AND CODE P.png",
           },
           {
            profileImage: "/image/warmerfashion.jpg",
            profileName: "Amanda Williams",
            userHandle: "iAmandaWilliams",
            textArea: "this is the very basic level of coding and i am glad this project is going out very smoothly even more than i expect, exclusive perf with all the amazing fragrance that you can't imagine",
            mainImage: "/image/warmerfashion.jpg",
            brandName: "Paris Fume",
            position: "scento",
            level: "warsaw",
            platform: "$10",
            approve: "55k",
            reject: "12k",
            fair:   "fair",
       good: "good",
       best: "best",
       unacceptable: "unacceptable",
       undecided: "undecided",
       numFair: "3k",
            numGood: "100",
            numBest: "1.5m",
            numUnacceptable: "12k",
            numUndecided: "4",
            bannerImage: "/image/THINK AND CODE P.png",
            info: "I am a Biomedical Technologist, CEO Think and Code Academy",
            userLocation: "Jos, Plateau",
            birthday: "May 15, 1990",
            joined: "December 2020",
            Admiring: "900",
            Admiriers: "1.5m"
           },
           {
            _id: "4",
            profileImage: "/image/Screenshot (13).png",
            profileName: "Oscar Inspires",
            userHandle: "iOscarInspires",
            textArea:"this is the very basic level of coding and i am glad this project is going out very smoothly even more than i expect, exclusive perf with all the amazing fragrance that you can't imagine",
            mainImage: "/image/WIN_20200723_15_43_50_Pro.jpg",
            brandName: "MAGA Nigeria",
            position: "President",
            level: "National",
            platform: "pdp",
            approve: "1.5m",
            reject: "32k",
            bannerImage: "/image/THINK AND CODE P.png",
            info: "I am a Biomedical Technologist, CEO Think and Code Academy",
            userLocation: "Jos, Plateau",
            birthday: "May 15, 1990",
            joined: "December 2020",
            Admiring: "900",
            Admiriers: "1.5m"
           },
           {
            _id: "5",
            profileImage: "/image/Screenshot_20200413-191114.jpg",
            profileName: "Oscar Inspires",
            userHandle: "iOscarInspires",
            bannerImage: "/image/THINK AND CODE P.png",
            textArea: "this is the very basic level of coding and i am glad this project is going out very smoothly even more than i expect..",
            mainImage: "/image/Screenshot_20200413-191114.jpg",
            brandName: "MAGA Nigeria",
            position: "President",
            level: "National",
            platform: "ydp",
            approve: "1.5m",
            reject: "32k",
            fair:   "fair",
       good: "good",
       best: "best",
       unacceptable: "unacceptable",
       undecided: "undecided",
       numFair: "3k",
            numGood: "100",
            numBest: "1.5m",
            numUnacceptable: "12k",
            numUndecided: "4",
            info: "I am a Biomedical Technologist, CEO Think and Code Academy",
            userLocation: "Jos, Plateau",
            birthday: "May 15, 1990",
            joined: "December 2020",
            Admiring: "900",
            Admiriers: "1.5m"
           },
           {
            profileImage: "/image/Screenshot (13).png",
            profileName: "Oscar Inspires",
            userHandle: "iOscarInspires",
            textArea: "this is the very basic level of coding and i am glad this project is going out very smoothly even more than i expect..",
            mainImage: "/image/WIN_20200723_15_43_50_Pro.jpg",
            brandName: "MAGA Nigeria",
            position: "President",
            level: "National",
            platform: "pdp",
            approve: "1.5m",
            reject: "32k",
            fair:   "fair",
       good: "good",
       best: "best",
       unacceptable: "unacceptable",
       undecided: "undecided",
       numFair: "3k",
            numGood: "100",
            numBest: "1.5m",
            numUnacceptable: "12k",
            numUndecided: "4",
            info: "I am a Biomedical Technologist, CEO Think and Code Academy",
            userLocation: "Jos, Plateau",
            birthday: "May 15, 1990",
            joined: "December 2020",
            Admiring: "900",
            Admiriers: "1.5m"
           },
           {
            profileImage: "/image/Screenshot (13).png",
            profileName: "Oscar Inspires",
            userHandle: "iOscarInspires",
            textArea: "this is the very basic level of coding and i am glad this project is going out very smoothly even more than i expect..",
            mainImage: "/image/WIN_20200723_15_43_50_Pro.jpg",
            brandName: "MAGA Nigeria",
            position: "President",
            level: "National",
            platform: "pdp",
            approve: "1.5m",
            reject: "32k",
            fair:   "fair",
       good: "good",
       best: "best",
       unacceptable: "unacceptable",
       undecided: "undecided",
       numFair: "3k",
            numGood: "100",
            numBest: "1.5m",
            numUnacceptable: "12k",
            numUndecided: "4",
            info: "I am a Biomedical Technologist, CEO Think and Code Academy",
            userLocation: "Jos, Plateau",
            birthday: "May 15, 1990",
            joined: "December 2020",
            Admiring: "900",
            Admiriers: "1.5m"
           },
           {
            profileImage: "/image/Screenshot_20200413-191114.jpg",
            profileName: "Lake Wood",
            userHandle: "iOscarInspires",
            textArea: "this is the very basic level of coding and i am glad this project is going out very smoothly even more than i expect..",
            mainImage: "/image/WIN_20200723_15_43_50_Pro.jpg",
            brandName: "Senate",
            position: "President",
            level: "plateau",
            platform: "apc",
            approve: "1m",
            reject: "8k",
            fair:   "fair",
       good: "good",
       best: "best",
       unacceptable: "unacceptable",
       undecided: "undecided",
       numFair: "3k",
            numGood: "100",
            numBest: "1.5m",
            numUnacceptable: "12k",
            numUndecided: "4",
            info: "I am a Biomedical Technologist, CEO Think and Code Academy",
            userLocation: "Jos, Plateau",
            birthday: "May 15, 1990",
            joined: "December 2020",
            Admiring: "900",
            Admiriers: "1.5m"
           },
           {
            profileImage: "/image/Screenshot (13).png",
            profileName: "Oscar Inspires",
            userHandle: "iOscarInspires",
            textArea: "this is the very basic level of coding and i am glad this project is going out very smoothly even more than i expect..",
            mainImage: "/image/WIN_20200723_15_43_50_Pro.jpg",
            brandName: "MAGA Nigeria",
            position: "President",
            level: "National",
            platform: "pdp",
            approve: "1.5m",
            reject: "32k",
            fair:   "fair",
       good: "good",
       best: "best",
       unacceptable: "unacceptable",
       undecided: "undecided",
       numFair: "3k",
            numGood: "100",
            numBest: "1.5m",
            numUnacceptable: "12k",
            numUndecided: "4",
            info: "I am a Biomedical Technologist, CEO Think and Code Academy",
            userLocation: "Jos, Plateau",
            birthday: "May 15, 1990",
            joined: "December 2020",
            Admiring: "900",
            Admiriers: "1.5m"
           },
           {
            profileImage: "/image/Screenshot (13).png",
            profileName: "Maria Uche",
            userHandle: "imariauche",
            textArea: "this is the very basic level of coding and i am glad this project is going out very smoothly even more than i expect..",
            mainImage: "/image/WIN_20200723_15_43_50_Pro.jpg",
            brandName: "MAGA Nigeria",
            position: "President",
            level: "National",
            platform: "pdp",
            approve: "1.5m",
            reject: "32k",
            fair:   "fair",
            good: "good",
            best: "best",
            unacceptable: "unacceptable",
            undecided: "undecided",
            numFair: "3k",
            numGood: "100",
            numBest: "1.5m",
            numUnacceptable: "12k",
            numUndecided: "4",
            info: "I am a Biomedical Technologist, CEO Think and Code Academy",
            userLocation: "Jos, Plateau",
            birthday: "May 15, 1990",
            joined: "December 2020",
            Admiring: "900",
            Admiriers: "1.5m"
           },
           {
            profileImage: "/image/Screenshot (13).png",
            profileName: "Oscar Inspires",
            choiceHandle: "iOscarInspires",
            textArea: "this is the very basic level of coding and i am glad this project is going out very smoothly even more than i expect..",
            mainImage: "/image/WIN_20200723_15_43_50_Pro.jpg",
            brandName: "MAGA Nigeria",
            position: "President",
            level: "National",
            platform: "pdp",
            approve: "1.5m",
            reject: "32k",
            fair:   "fair",
           good: "good",
           best: "best",
           unacceptable: "unacceptable",
           undecided: "undecided",
           numFair: "3k",
            numGood: "100",
            numBest: "1.5m",
            numUnacceptable: "12k",
            numUndecided: "4",
            info: "I am a Biomedical Technologist, CEO Think and Code Academy",
            userLocation: "Jos, Plateau",
            birthday: "May 15, 1990",
            joined: "December 2020",
            Admiring: "900",
            Admiriers: "1.5m"
           },
           {
            profileImage: "/image/Screenshot (13).png",
            profileName: "Francis Zuma",
            userHandle: "iFZuma",
            textArea: "this is the very basic level of coding and i am glad this project is going out very smoothly even more than i expect..",
            mainImage: "/image/WIN_20200723_15_43_50_Pro.jpg",
            brandName: "zuma limited",
            position: "New",
            level: "Lagos",
            platform: "$200",
            approve: "1.5m",
            reject: "32k",
            fair:   "fair",
            good: "good",
            best: "best",
            unacceptable: "unacceptable",
            undecided: "undecided",
            numFair: "3k",
            numGood: "100",
            numBest: "1.5m",
            numUnacceptable: "12k",
            numUndecided: "4",
            info: "I am a Biomedical Technologist, CEO Think and Code Academy",
            userLocation: "Jos, Plateau",
            birthday: "May 28, 1990",
            joined: "December 2020",
            Admiring: "900",
            Admiriers: "1.5m"
           },
    ]
}
export default data;
