export const CONTENT_LIST_REQUEST = "CONTENT_LIST_REQUEST";
export const CONTENT_LIST_SUCCESS = "CONTENT_LIST_SUCCESS";
export const CONTENT_LIST_FAIL = "CONTENT_LIST_FAIL";

export const CONTENT_DETAILS_REQUEST = "CONTENT_DETAILS_REQUEST";
export const CONTENT_DETAILS_SUCCESS = "CONTENT_DETAILS_SUCCESS";
export const CONTENT_DETAILS_FAIL = "CONTENT_DETAILS_FAIL";
